### ISSUE TITLE
[Bug] plex 没生效 

### ISSUE THREAD

**Issue by iceloon** [metatube-community/metatube-plex-plugins#38]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube.bundle Version

v2024.302.2109.0

### MetaTube Server Version

1.2.3

### Description

metatube服务器正常，但是plex用插件刮削无任何返回

### MetaTube Server

https://metatube-cameloter.koyeb.app

### Plex Logs

[Plex Media Server Logs_2024-04-07_10-31-20.zip](https://github.com/metatube-community/metatube-plex-plugins/files/14895595/Plex.Media.Server.Logs_2024-04-07_10-31-20.zip)

### MetaTube Server Logs

[metatube-metatube.txt](https://github.com/metatube-community/metatube-plex-plugins/files/14895597/metatube-metatube.txt)

**Comment by iceloon** [comment]
plex server 版本 1.40.1.8227-7000

**Comment by iceloon** [comment]
[metatube-metatube (1).txt](https://github.com/metatube-community/metatube-plex-plugins/files/14895673/metatube-metatube.1.txt)

**Comment by sheepzacks** [comment]
我最近发现koyeb部署的后端能ping通有日志，但是浏览器打不开，所以插件访问不到，我还没找到解决方案，不知道有谁能发现解决方案

**Comment by sheepzacks** [comment]
应该是部分人才会出现的问题，我换了不同的网络，发现这个问题应该是你运行代理那台电脑被墙了，访问不到部署在koyeb的后端，这是我目前发现的，起码适用于我

**Comment by iceloon** [comment]
> 应该是部分人才会出现的问题，我换了不同的网络，发现这个问题应该是你运行代理那台电脑被墙了，访问不到部署在koyeb的后端，这是我目前发现的，起码适用于我

感谢，最近还是换回了mdcx

**Comment by sheepzacks** [comment]
假设你后续还想用，我目前找到的解决方案是用dns服务商的反向代理到koyeb的后端，使用也非常稳定
