### ISSUE TITLE
[Bug] 刮削不生效

### ISSUE THREAD

**Issue by kuanos** [metatube-community/metatube-plex-plugins#40]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://metatube-community.github.io/wiki/), especially the [FAQ](https://metatube-community.github.io/faq/) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube.bundle Version

v2024.512.1734.0

### MetaTube Server Version

1.2.3

### What OS are you seeing the problem on?

macOS

### Description

无法正常刮削内容，验证代理无问题

### MetaTube Server

[GORM] 2024/05/19 08:21:48 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
[0.691ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "RCT-005" COLLATE NOCASE OR id = "RCT-005" COLLATE NOCASE
[GIN] 2024/05/19 - 08:21:48 | 404 |   32.365235ms |        10.0.3.1 | GET      "/v1/movies/search?q=RCT-005"
{"level":"info","ts":1716106918.5381665,"caller":"engine/movie.go:137","msg":"Search keyword Rct 005: fc2hub(140.994µs): invalid keyword HEYZO(193.032µs): invalid id HeyDouga(302.023µs): invalid id Caribbeancom(1.01501ms): invalid id CaribbeancomPR(1.082964ms): invalid id MYWIFE(1.204553ms): invalid id MURAMURA(1.320221ms): invalid id FC2(1.554147ms): invalid id C0930(1.698598ms): invalid id XXX-AV(1.72482ms): invalid id H0930(1.780775ms): invalid id AIRAV(1.790797ms): invalid keyword 1Pondo(1.87662ms): invalid id Getchu(1.954896ms): invalid id Gcolle(2.037637ms): invalid id H4610(2.105742ms): invalid id TOKYO-HOT(2.470818ms): invalid keyword 10musume(2.55667ms): invalid id DUGA(3.045441ms): Get \"https://duga.jp/search/=/q=RCT%20005/\": proxyconnect tcp: EOF JAV321(3.629835ms): Post \"https://www.jav321.com/search\": proxyconnect tcp: EOF AVE(3.73038ms): Get \"https://www.aventertainments.com/search_Products.aspx?languageID=2&dept_id=29&keyword=RCT+005&searchby=keyword\": proxyconnect tcp: EOF FANZA(3.833897ms): Get \"https://www.dmm.co.jp/search/=/searchstr=rct+005/limit=120/sort=date/\": proxyconnect tcp: EOF JavBus(3.926795ms): <nil> PACOPACOMAMA(3.993879ms): invalid id KIN8(4.08171ms): invalid id AVBASE(4.143705ms): Get \"https://www.avbase.net/\": proxyconnect tcp: EOF Pcolle(4.196461ms): invalid id MGS(4.475549ms): Get \"https://www.mgstage.com/search/cSearch.php?search_word=RCT+005\": proxyconnect tcp: EOF SOD(4.454156ms): Get \"https://ec.sod.co.jp/prime/videos/genre/?search_type=1&sodsearch=RCT+005\": proxyconnect tcp: EOF FALENO(5.236946ms): Get \"https://faleno.jp/top/?s=rct+005\": proxyconnect tcp: EOF DAHLIA(5.941014ms): Get \"https://dahlia-av.jp/?s=rct+005\": proxyconnect tcp: EOF ARZON(6.039867ms): Get \"https://www.arzon.jp/itemlist.html?&q=RCT+005&t=all&m=all&s=all&mkt=all&disp=30&sort=-udate\": proxyconnect tcp: EOF"}
[GORM] 2024/05/19 08:21:58 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
[0.499ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "Rct 005" COLLATE NOCASE OR id = "Rct 005" COLLATE NOCASE
[GIN] 2024/05/19 - 08:21:58 | 404 |    7.618153ms |        10.0.3.1 | GET      "/v1/movies/search?q=Rct+005"

### Plex Logs

查找发现没有metatube插件日志

### MetaTube Server Logs

[GORM] 2024/05/19 08:21:48 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
[0.691ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "RCT-005" COLLATE NOCASE OR id = "RCT-005" COLLATE NOCASE
[GIN] 2024/05/19 - 08:21:48 | 404 |   32.365235ms |        10.0.3.1 | GET      "/v1/movies/search?q=RCT-005"
{"level":"info","ts":1716106918.5381665,"caller":"engine/movie.go:137","msg":"Search keyword Rct 005: fc2hub(140.994µs): invalid keyword HEYZO(193.032µs): invalid id HeyDouga(302.023µs): invalid id Caribbeancom(1.01501ms): invalid id CaribbeancomPR(1.082964ms): invalid id MYWIFE(1.204553ms): invalid id MURAMURA(1.320221ms): invalid id FC2(1.554147ms): invalid id C0930(1.698598ms): invalid id XXX-AV(1.72482ms): invalid id H0930(1.780775ms): invalid id AIRAV(1.790797ms): invalid keyword 1Pondo(1.87662ms): invalid id Getchu(1.954896ms): invalid id Gcolle(2.037637ms): invalid id H4610(2.105742ms): invalid id TOKYO-HOT(2.470818ms): invalid keyword 10musume(2.55667ms): invalid id DUGA(3.045441ms): Get \"https://duga.jp/search/=/q=RCT%20005/\": proxyconnect tcp: EOF JAV321(3.629835ms): Post \"https://www.jav321.com/search\": proxyconnect tcp: EOF AVE(3.73038ms): Get \"https://www.aventertainments.com/search_Products.aspx?languageID=2&dept_id=29&keyword=RCT+005&searchby=keyword\": proxyconnect tcp: EOF FANZA(3.833897ms): Get \"https://www.dmm.co.jp/search/=/searchstr=rct+005/limit=120/sort=date/\": proxyconnect tcp: EOF JavBus(3.926795ms): <nil> PACOPACOMAMA(3.993879ms): invalid id KIN8(4.08171ms): invalid id AVBASE(4.143705ms): Get \"https://www.avbase.net/\": proxyconnect tcp: EOF Pcolle(4.196461ms): invalid id MGS(4.475549ms): Get \"https://www.mgstage.com/search/cSearch.php?search_word=RCT+005\": proxyconnect tcp: EOF SOD(4.454156ms): Get \"https://ec.sod.co.jp/prime/videos/genre/?search_type=1&sodsearch=RCT+005\": proxyconnect tcp: EOF FALENO(5.236946ms): Get \"https://faleno.jp/top/?s=rct+005\": proxyconnect tcp: EOF DAHLIA(5.941014ms): Get \"https://dahlia-av.jp/?s=rct+005\": proxyconnect tcp: EOF ARZON(6.039867ms): Get \"https://www.arzon.jp/itemlist.html?&q=RCT+005&t=all&m=all&s=all&mkt=all&disp=30&sort=-udate\": proxyconnect tcp: EOF"}
[GORM] 2024/05/19 08:21:58 github.com/metatube-community/metatube-sdk-go/engine/movie.go:27
[0.499ms] [rows:0] SELECT * FROM `movie_metadata` WHERE number = "Rct 005" COLLATE NOCASE OR id = "Rct 005" COLLATE NOCASE
[GIN] 2024/05/19 - 08:21:58 | 404 |    7.618153ms |        10.0.3.1 | GET      "/v1/movies/search?q=Rct+005"

**Comment by pandazo** [comment]
same issue how to solve?
